---
title: "Jingxuan"
author: "Jingxuan He"
date: "February 2, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyverse)
library(httr)
library(rvest)
library(janitor)
library(stringr)
library(ggplot2)
library(hexbin)
library(plotly)
library(knitr)
library(DT)
library(lubridate)
library(car)
library(psych)

```

### Prepare the data
```{r}
data = read_csv("./pollution_us_2000_2016_short.csv") %>%
  clean_names() %>%
  mutate(date = mdy(date)) %>%
  arrange(date)
  
```

### Seperate the pollutant
```{r}
NO2_pollutant = data %>%
  select(state_code:date, no2_mean:no2_aqi)

O3_pollutant = data %>%
  select(state_code:date, o3_mean:o3_aqi)
  

SO2_pollutant = data %>%
  select(state_code:date, so2_mean:so2_aqi)

CO_pollutant = data %>%
  select(state_code:date, co_mean:co_aqi) 

pollutant = data %>%
  select(no2_aqi, o3_aqi, so2_aqi, co_aqi) %>%
  sample_n(5000)
  

```

### relationship between pollutants
```{r}
pairs.panels(pollutant, 
             method = "pearson", # correlation method
             density = TRUE,  # show density plots
             ellipses = TRUE # show correlation ellipses
             )
```

### Location scale
```{r}
pollution_aqi_state = data %>% 
  select(state, date, no2_aqi, o3_aqi, so2_aqi, co_aqi) %>% 
  gather(key = pollutants, value = aqi, no2_aqi:co_aqi) %>% 
  separate(date, into = c("year", "month", "day"), sep = "-")%>%
  mutate(pollutants = stringr::str_replace(pollutants,"_aqi","")) %>% 
  group_by(pollutants, state) %>% 
  mutate(mean_aqi_state = mean(aqi, na.rm = TRUE),
         median_aqi_state = median(aqi, na.rm = TRUE)) %>% 
  ungroup()

median  = pollution_aqi_state %>% 
  filter(pollutants == "no2") %>%
  select(state, median_aqi_state) %>%
  mutate(name = forcats::fct_reorder(state, median_aqi_state)) %>% 
  distinct()
  
pollution_aqi_state %>% 
  filter(pollutants == "no2", 
         state == "Massachusetts"| state =="Country Of Mexico"| state =="Hawaii"| state =="Oregon"| state =="Alabama"|state =="Nevada"|state =="New Mexico"|state =="Tennessee"|state =="Utah"|state =="Wyoming") %>%
  mutate(name = forcats::fct_reorder(state, median_aqi_state)) %>%
  ggplot(aes(x = name, y = aqi)) +
  geom_boxplot(outlier.alpha = 0.1) +
  labs(x ="States", y = "Aqi for all states", title= "NO2 aqi") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

plot1 = pollution_aqi_state %>% 
  filter(pollutants == "no2") %>%
  mutate(name = forcats::fct_reorder(state, mean_aqi_state)) %>%
  ggplot(aes(x = name, y = mean_aqi_state, color = pollutants)) +
  geom_boxplot() +
  geom_line(aes(group = pollutants, color = pollutants)) +
  labs(x ="Months (year 2010- 2016)", y = "mean aqi for all states", title= "Change of mean aqi of all states for 6 years") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1), legend.position = "none")
```